### ISSUE TITLE
Imports are order dependent

### ISSUE THREAD

**Issue by matthewjasper** [Rust-GCC/gccrs#2232]
I tried this code (from general experimentation with the compiler):

```rust
mod a {
    pub fn f() {}
}

// Compiles if moved below b
mod c {
    use crate::b::{f, g};

    pub fn h() {
        f();
        g();
    }
}

mod b {
    pub use crate::a::f;

    pub fn g() {
        f();
    }
}
```

I expected to see this happen: Compiles

Instead, this happened: error

```text
<source>:6:20: error: cannot find simple path segment 'f' in this scope
    6 |     use crate::b::{f, g};
      |                    ^
<source>:9:9: error: Cannot find path 'f' in this scope
    9 |         f();
      |         
```

### Meta

- What version of Rust GCC were you using, git sha if possible.
gccrs (Compiler-Explorer-Build-gcc-c7b7e297ea4b688ef9fb51a8aee2a8b2af39ac1c-binutils-2.40) 13.0.1 20230417 (experimental)

**Comment by CohenArthur** [comment]
I'm wondering if this works in Rust because imports are resolved during early name resolution, but function calls are resolved during late name resolution - so a long time after the `use` statement has been properly handled

**Comment by powerboat9** [comment]
https://rustc-dev-guide.rust-lang.org/macro-expansion.html

It looks like import resolution should be attempted multiple times.

**Comment by liamnaddell** [comment]
Seems to work with NR2.0 :)

```
TRS-E14 gccrs-build :( $ gccrs a.rs
a.rs:7:20: error: cannot find simple path segment ‘f’ in this scope
    7 |     use crate::b::{f, g};
      |                    ^
a.rs:10:9: error: Cannot find path ‘f’ in this scope [E0433]
   10 |         f();
      |         ^
TRS-E14 gccrs-build :( $ gccrs -frust-name-resolution-2.0 a.rs
/usr/bin/ld: /lib/../lib64/crt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
collect2: error: ld returned 1 exit status
```

**Comment by matthewjasper** [comment]
And now NR2.0 is the default.
