### PR TITLE
Fix '#include <algorithm>' [#159]

### PR DESCRIPTION
**Pull request by tschwinge**
... recently introduced in #1044 commit 35ca685200830626e5abd623f65a850649beace2
"macros: Add base functions to check for follow-set ambiguities".

GCC doesn't like that:

    In file included from [...]
    ./mm_malloc.h:42:12: error: attempt to use poisoned "malloc"
         return malloc (__size);
                ^

See commit e7b3f654f2ab0400c95c0517387a9ad645a5c4cd, for example.

### CODE REVIEW

**Review by CohenArthur — APPROVED** [review]
Oh, I had no idea. Sorry about that! No warnings on my end or on bors's, or even on the buildbot. I'll keep it in mind!

**Comment by tschwinge** [comment]
No worries.  Actually, I also don't know the reason for this.

I had seen that there's more cleanup to be done in that area.  For example, see in `gcc/rust/rust-system.h`: _These must be included before the #poison declarations in system.h._  These also ought to be handled differently (per GCC standards).  But that's for another day.

---

bors: merge
